/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Thu Jan 29 14:11:54 2026


#include "SimulatedWorld_nws_ros2_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(SimulatedWorld_nws_ros2ParamsCOMPONENT, "yarp.device.SimulatedWorld_nws_ros2")
}


SimulatedWorld_nws_ros2_ParamsParser::SimulatedWorld_nws_ros2_ParamsParser()
{
}


std::vector<std::string> SimulatedWorld_nws_ros2_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("node_name");
    params.push_back("namespace");
    params.push_back("makesphere");
    params.push_back("makebox");
    params.push_back("makecylinder");
    params.push_back("makeframe");
    params.push_back("makemodel");
    params.push_back("changecolor");
    params.push_back("setpose");
    params.push_back("enablegravity");
    params.push_back("enablecollision");
    params.push_back("getpose");
    params.push_back("deleteobject");
    params.push_back("deleteall");
    params.push_back("getlist");
    params.push_back("attach");
    params.push_back("detach");
    params.push_back("rename");
    return params;
}


bool SimulatedWorld_nws_ros2_ParamsParser::getParamValue(const std::string& paramName, std::string& paramValue) const
{
    if (paramName =="node_name")
    {
        paramValue = m_node_name;
        return true;
    }
    if (paramName =="namespace")
    {
        paramValue = m_namespace;
        return true;
    }
    if (paramName =="makesphere")
    {
        paramValue = m_makesphere;
        return true;
    }
    if (paramName =="makebox")
    {
        paramValue = m_makebox;
        return true;
    }
    if (paramName =="makecylinder")
    {
        paramValue = m_makecylinder;
        return true;
    }
    if (paramName =="makeframe")
    {
        paramValue = m_makeframe;
        return true;
    }
    if (paramName =="makemodel")
    {
        paramValue = m_makemodel;
        return true;
    }
    if (paramName =="changecolor")
    {
        paramValue = m_changecolor;
        return true;
    }
    if (paramName =="setpose")
    {
        paramValue = m_setpose;
        return true;
    }
    if (paramName =="enablegravity")
    {
        paramValue = m_enablegravity;
        return true;
    }
    if (paramName =="enablecollision")
    {
        paramValue = m_enablecollision;
        return true;
    }
    if (paramName =="getpose")
    {
        paramValue = m_getpose;
        return true;
    }
    if (paramName =="deleteobject")
    {
        paramValue = m_deleteobject;
        return true;
    }
    if (paramName =="deleteall")
    {
        paramValue = m_deleteall;
        return true;
    }
    if (paramName =="getlist")
    {
        paramValue = m_getlist;
        return true;
    }
    if (paramName =="attach")
    {
        paramValue = m_attach;
        return true;
    }
    if (paramName =="detach")
    {
        paramValue = m_detach;
        return true;
    }
    if (paramName =="rename")
    {
        paramValue = m_rename;
        return true;
    }

    yError() <<"parameter '" << paramName << "' was not found";
    return false;

}


std::string SimulatedWorld_nws_ros2_ParamsParser::getConfiguration() const
{
    //This is a sub-optimal solution.
    //Ideally getConfiguration() should return all parameters but it is currently
    //returning only user provided parameters (excluding default values)
    //This behaviour will be fixed in the near future.
    std::string s_cfg = m_provided_configuration;
    return s_cfg;
}

bool      SimulatedWorld_nws_ros2_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    m_provided_configuration = config.toString();
    yarp::os::Property prop_check(m_provided_configuration.c_str());
    //Parser of parameter node_name
    {
        if (config.check("node_name"))
        {
            m_node_name = config.find("node_name").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'node_name' using value:" << m_node_name;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'node_name' using DEFAULT value:" << m_node_name;
        }
        prop_check.unput("node_name");
    }

    //Parser of parameter namespace
    {
        if (config.check("namespace"))
        {
            m_namespace = config.find("namespace").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'namespace' using value:" << m_namespace;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'namespace' using DEFAULT value:" << m_namespace;
        }
        prop_check.unput("namespace");
    }

    //Parser of parameter makesphere
    {
        if (config.check("makesphere"))
        {
            m_makesphere = config.find("makesphere").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'makesphere' using value:" << m_makesphere;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'makesphere' using DEFAULT value:" << m_makesphere;
        }
        prop_check.unput("makesphere");
    }

    //Parser of parameter makebox
    {
        if (config.check("makebox"))
        {
            m_makebox = config.find("makebox").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'makebox' using value:" << m_makebox;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'makebox' using DEFAULT value:" << m_makebox;
        }
        prop_check.unput("makebox");
    }

    //Parser of parameter makecylinder
    {
        if (config.check("makecylinder"))
        {
            m_makecylinder = config.find("makecylinder").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'makecylinder' using value:" << m_makecylinder;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'makecylinder' using DEFAULT value:" << m_makecylinder;
        }
        prop_check.unput("makecylinder");
    }

    //Parser of parameter makeframe
    {
        if (config.check("makeframe"))
        {
            m_makeframe = config.find("makeframe").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'makeframe' using value:" << m_makeframe;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'makeframe' using DEFAULT value:" << m_makeframe;
        }
        prop_check.unput("makeframe");
    }

    //Parser of parameter makemodel
    {
        if (config.check("makemodel"))
        {
            m_makemodel = config.find("makemodel").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'makemodel' using value:" << m_makemodel;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'makemodel' using DEFAULT value:" << m_makemodel;
        }
        prop_check.unput("makemodel");
    }

    //Parser of parameter changecolor
    {
        if (config.check("changecolor"))
        {
            m_changecolor = config.find("changecolor").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'changecolor' using value:" << m_changecolor;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'changecolor' using DEFAULT value:" << m_changecolor;
        }
        prop_check.unput("changecolor");
    }

    //Parser of parameter setpose
    {
        if (config.check("setpose"))
        {
            m_setpose = config.find("setpose").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'setpose' using value:" << m_setpose;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'setpose' using DEFAULT value:" << m_setpose;
        }
        prop_check.unput("setpose");
    }

    //Parser of parameter enablegravity
    {
        if (config.check("enablegravity"))
        {
            m_enablegravity = config.find("enablegravity").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'enablegravity' using value:" << m_enablegravity;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'enablegravity' using DEFAULT value:" << m_enablegravity;
        }
        prop_check.unput("enablegravity");
    }

    //Parser of parameter enablecollision
    {
        if (config.check("enablecollision"))
        {
            m_enablecollision = config.find("enablecollision").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'enablecollision' using value:" << m_enablecollision;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'enablecollision' using DEFAULT value:" << m_enablecollision;
        }
        prop_check.unput("enablecollision");
    }

    //Parser of parameter getpose
    {
        if (config.check("getpose"))
        {
            m_getpose = config.find("getpose").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'getpose' using value:" << m_getpose;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'getpose' using DEFAULT value:" << m_getpose;
        }
        prop_check.unput("getpose");
    }

    //Parser of parameter deleteobject
    {
        if (config.check("deleteobject"))
        {
            m_deleteobject = config.find("deleteobject").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'deleteobject' using value:" << m_deleteobject;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'deleteobject' using DEFAULT value:" << m_deleteobject;
        }
        prop_check.unput("deleteobject");
    }

    //Parser of parameter deleteall
    {
        if (config.check("deleteall"))
        {
            m_deleteall = config.find("deleteall").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'deleteall' using value:" << m_deleteall;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'deleteall' using DEFAULT value:" << m_deleteall;
        }
        prop_check.unput("deleteall");
    }

    //Parser of parameter getlist
    {
        if (config.check("getlist"))
        {
            m_getlist = config.find("getlist").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'getlist' using value:" << m_getlist;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'getlist' using DEFAULT value:" << m_getlist;
        }
        prop_check.unput("getlist");
    }

    //Parser of parameter attach
    {
        if (config.check("attach"))
        {
            m_attach = config.find("attach").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'attach' using value:" << m_attach;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'attach' using DEFAULT value:" << m_attach;
        }
        prop_check.unput("attach");
    }

    //Parser of parameter detach
    {
        if (config.check("detach"))
        {
            m_detach = config.find("detach").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'detach' using value:" << m_detach;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'detach' using DEFAULT value:" << m_detach;
        }
        prop_check.unput("detach");
    }

    //Parser of parameter rename
    {
        if (config.check("rename"))
        {
            m_rename = config.find("rename").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'rename' using value:" << m_rename;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'rename' using DEFAULT value:" << m_rename;
        }
        prop_check.unput("rename");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      SimulatedWorld_nws_ros2_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: SimulatedWorld_nws_ros2\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'node_name': The ROS2 node name\n");
    doc = doc + std::string("'namespace': optional namespace for ros2 node\n");
    doc = doc + std::string("'makesphere': ROS2 service name for makeSphere\n");
    doc = doc + std::string("'makebox': ROS2 service name for makeBox\n");
    doc = doc + std::string("'makecylinder': ROS2 service name for makeCylinder\n");
    doc = doc + std::string("'makeframe': ROS2 service name for makeFrame\n");
    doc = doc + std::string("'makemodel': ROS2 service name for makeModel\n");
    doc = doc + std::string("'changecolor': ROS2 service name for changeColor\n");
    doc = doc + std::string("'setpose': ROS2 service name for setPose\n");
    doc = doc + std::string("'enablegravity': ROS2 service name for enableGravity\n");
    doc = doc + std::string("'enablecollision': ROS2 service name for enableCollision\n");
    doc = doc + std::string("'getpose': ROS2 service name for getPose\n");
    doc = doc + std::string("'deleteobject': ROS2 service name for deleteObject\n");
    doc = doc + std::string("'deleteall': ROS2 service name for deleteAll\n");
    doc = doc + std::string("'getlist': ROS2 service name for getList\n");
    doc = doc + std::string("'attach': ROS2 service name for attach\n");
    doc = doc + std::string("'detach': ROS2 service name for detach\n");
    doc = doc + std::string("'rename': ROS2 service name for rename\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device simulatedWorld_nws_ros2 --node_name simulatedWorld_nws_ros2 --namespace <optional_value> --makesphere makeSphere --makebox makeBox --makecylinder makeCylinder --makeframe makeFrame --makemodel makeModel --changecolor changeColor --setpose setPose --enablegravity enableGravity --enablecollision enableCollision --getpose getPose --deleteobject deleteObject --deleteall deleteAll --getlist getList --attach attach --detach detach --rename rename\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device simulatedWorld_nws_ros2\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
