/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Wed Feb 25 10:20:51 2026


#include "SimulatedWorld_nws_ros2_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(SimulatedWorld_nws_ros2ParamsCOMPONENT, "yarp.device.SimulatedWorld_nws_ros2")
}


SimulatedWorld_nws_ros2_ParamsParser::SimulatedWorld_nws_ros2_ParamsParser()
{
}


std::vector<std::string> SimulatedWorld_nws_ros2_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("node_name");
    params.push_back("namespace");
    params.push_back("makesphere_servicename");
    params.push_back("makebox_servicename");
    params.push_back("makecylinder_servicename");
    params.push_back("makeframe_servicename");
    params.push_back("makemodel_servicename");
    params.push_back("makeactor_servicename");
    params.push_back("changecolor_servicename");
    params.push_back("setpose_servicename");
    params.push_back("enablegravity_servicename");
    params.push_back("enablecollision_servicename");
    params.push_back("getpose_servicename");
    params.push_back("deleteobject_servicename");
    params.push_back("deleteall_servicename");
    params.push_back("getlist_servicename");
    params.push_back("attach_servicename");
    params.push_back("detach_servicename");
    params.push_back("rename_servicename");
    return params;
}


bool SimulatedWorld_nws_ros2_ParamsParser::getParamValue(const std::string& paramName, std::string& paramValue) const
{
    if (paramName =="node_name")
    {
        paramValue = m_node_name;
        return true;
    }
    if (paramName =="namespace")
    {
        paramValue = m_namespace;
        return true;
    }
    if (paramName =="makesphere_servicename")
    {
        paramValue = m_makesphere_servicename;
        return true;
    }
    if (paramName =="makebox_servicename")
    {
        paramValue = m_makebox_servicename;
        return true;
    }
    if (paramName =="makecylinder_servicename")
    {
        paramValue = m_makecylinder_servicename;
        return true;
    }
    if (paramName =="makeframe_servicename")
    {
        paramValue = m_makeframe_servicename;
        return true;
    }
    if (paramName =="makemodel_servicename")
    {
        paramValue = m_makemodel_servicename;
        return true;
    }
    if (paramName =="makeactor_servicename")
    {
        paramValue = m_makeactor_servicename;
        return true;
    }
    if (paramName =="changecolor_servicename")
    {
        paramValue = m_changecolor_servicename;
        return true;
    }
    if (paramName =="setpose_servicename")
    {
        paramValue = m_setpose_servicename;
        return true;
    }
    if (paramName =="enablegravity_servicename")
    {
        paramValue = m_enablegravity_servicename;
        return true;
    }
    if (paramName =="enablecollision_servicename")
    {
        paramValue = m_enablecollision_servicename;
        return true;
    }
    if (paramName =="getpose_servicename")
    {
        paramValue = m_getpose_servicename;
        return true;
    }
    if (paramName =="deleteobject_servicename")
    {
        paramValue = m_deleteobject_servicename;
        return true;
    }
    if (paramName =="deleteall_servicename")
    {
        paramValue = m_deleteall_servicename;
        return true;
    }
    if (paramName =="getlist_servicename")
    {
        paramValue = m_getlist_servicename;
        return true;
    }
    if (paramName =="attach_servicename")
    {
        paramValue = m_attach_servicename;
        return true;
    }
    if (paramName =="detach_servicename")
    {
        paramValue = m_detach_servicename;
        return true;
    }
    if (paramName =="rename_servicename")
    {
        paramValue = m_rename_servicename;
        return true;
    }

    yError() <<"parameter '" << paramName << "' was not found";
    return false;

}


std::string SimulatedWorld_nws_ros2_ParamsParser::getConfiguration() const
{
    //This is a sub-optimal solution.
    //Ideally getConfiguration() should return all parameters but it is currently
    //returning only user provided parameters (excluding default values)
    //This behaviour will be fixed in the near future.
    std::string s_cfg = m_provided_configuration;
    return s_cfg;
}

bool      SimulatedWorld_nws_ros2_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    m_provided_configuration = config.toString();
    yarp::os::Property prop_check(m_provided_configuration.c_str());
    //Parser of parameter node_name
    {
        if (config.check("node_name"))
        {
            m_node_name = config.find("node_name").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'node_name' using value:" << m_node_name;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'node_name' using DEFAULT value:" << m_node_name;
        }
        prop_check.unput("node_name");
    }

    //Parser of parameter namespace
    {
        if (config.check("namespace"))
        {
            m_namespace = config.find("namespace").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'namespace' using value:" << m_namespace;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'namespace' using DEFAULT value:" << m_namespace;
        }
        prop_check.unput("namespace");
    }

    //Parser of parameter makesphere_servicename
    {
        if (config.check("makesphere_servicename"))
        {
            m_makesphere_servicename = config.find("makesphere_servicename").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'makesphere_servicename' using value:" << m_makesphere_servicename;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'makesphere_servicename' using DEFAULT value:" << m_makesphere_servicename;
        }
        prop_check.unput("makesphere_servicename");
    }

    //Parser of parameter makebox_servicename
    {
        if (config.check("makebox_servicename"))
        {
            m_makebox_servicename = config.find("makebox_servicename").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'makebox_servicename' using value:" << m_makebox_servicename;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'makebox_servicename' using DEFAULT value:" << m_makebox_servicename;
        }
        prop_check.unput("makebox_servicename");
    }

    //Parser of parameter makecylinder_servicename
    {
        if (config.check("makecylinder_servicename"))
        {
            m_makecylinder_servicename = config.find("makecylinder_servicename").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'makecylinder_servicename' using value:" << m_makecylinder_servicename;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'makecylinder_servicename' using DEFAULT value:" << m_makecylinder_servicename;
        }
        prop_check.unput("makecylinder_servicename");
    }

    //Parser of parameter makeframe_servicename
    {
        if (config.check("makeframe_servicename"))
        {
            m_makeframe_servicename = config.find("makeframe_servicename").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'makeframe_servicename' using value:" << m_makeframe_servicename;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'makeframe_servicename' using DEFAULT value:" << m_makeframe_servicename;
        }
        prop_check.unput("makeframe_servicename");
    }

    //Parser of parameter makemodel_servicename
    {
        if (config.check("makemodel_servicename"))
        {
            m_makemodel_servicename = config.find("makemodel_servicename").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'makemodel_servicename' using value:" << m_makemodel_servicename;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'makemodel_servicename' using DEFAULT value:" << m_makemodel_servicename;
        }
        prop_check.unput("makemodel_servicename");
    }

    //Parser of parameter makeactor_servicename
    {
        if (config.check("makeactor_servicename"))
        {
            m_makeactor_servicename = config.find("makeactor_servicename").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'makeactor_servicename' using value:" << m_makeactor_servicename;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'makeactor_servicename' using DEFAULT value:" << m_makeactor_servicename;
        }
        prop_check.unput("makeactor_servicename");
    }

    //Parser of parameter changecolor_servicename
    {
        if (config.check("changecolor_servicename"))
        {
            m_changecolor_servicename = config.find("changecolor_servicename").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'changecolor_servicename' using value:" << m_changecolor_servicename;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'changecolor_servicename' using DEFAULT value:" << m_changecolor_servicename;
        }
        prop_check.unput("changecolor_servicename");
    }

    //Parser of parameter setpose_servicename
    {
        if (config.check("setpose_servicename"))
        {
            m_setpose_servicename = config.find("setpose_servicename").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'setpose_servicename' using value:" << m_setpose_servicename;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'setpose_servicename' using DEFAULT value:" << m_setpose_servicename;
        }
        prop_check.unput("setpose_servicename");
    }

    //Parser of parameter enablegravity_servicename
    {
        if (config.check("enablegravity_servicename"))
        {
            m_enablegravity_servicename = config.find("enablegravity_servicename").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'enablegravity_servicename' using value:" << m_enablegravity_servicename;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'enablegravity_servicename' using DEFAULT value:" << m_enablegravity_servicename;
        }
        prop_check.unput("enablegravity_servicename");
    }

    //Parser of parameter enablecollision_servicename
    {
        if (config.check("enablecollision_servicename"))
        {
            m_enablecollision_servicename = config.find("enablecollision_servicename").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'enablecollision_servicename' using value:" << m_enablecollision_servicename;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'enablecollision_servicename' using DEFAULT value:" << m_enablecollision_servicename;
        }
        prop_check.unput("enablecollision_servicename");
    }

    //Parser of parameter getpose_servicename
    {
        if (config.check("getpose_servicename"))
        {
            m_getpose_servicename = config.find("getpose_servicename").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'getpose_servicename' using value:" << m_getpose_servicename;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'getpose_servicename' using DEFAULT value:" << m_getpose_servicename;
        }
        prop_check.unput("getpose_servicename");
    }

    //Parser of parameter deleteobject_servicename
    {
        if (config.check("deleteobject_servicename"))
        {
            m_deleteobject_servicename = config.find("deleteobject_servicename").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'deleteobject_servicename' using value:" << m_deleteobject_servicename;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'deleteobject_servicename' using DEFAULT value:" << m_deleteobject_servicename;
        }
        prop_check.unput("deleteobject_servicename");
    }

    //Parser of parameter deleteall_servicename
    {
        if (config.check("deleteall_servicename"))
        {
            m_deleteall_servicename = config.find("deleteall_servicename").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'deleteall_servicename' using value:" << m_deleteall_servicename;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'deleteall_servicename' using DEFAULT value:" << m_deleteall_servicename;
        }
        prop_check.unput("deleteall_servicename");
    }

    //Parser of parameter getlist_servicename
    {
        if (config.check("getlist_servicename"))
        {
            m_getlist_servicename = config.find("getlist_servicename").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'getlist_servicename' using value:" << m_getlist_servicename;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'getlist_servicename' using DEFAULT value:" << m_getlist_servicename;
        }
        prop_check.unput("getlist_servicename");
    }

    //Parser of parameter attach_servicename
    {
        if (config.check("attach_servicename"))
        {
            m_attach_servicename = config.find("attach_servicename").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'attach_servicename' using value:" << m_attach_servicename;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'attach_servicename' using DEFAULT value:" << m_attach_servicename;
        }
        prop_check.unput("attach_servicename");
    }

    //Parser of parameter detach_servicename
    {
        if (config.check("detach_servicename"))
        {
            m_detach_servicename = config.find("detach_servicename").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'detach_servicename' using value:" << m_detach_servicename;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'detach_servicename' using DEFAULT value:" << m_detach_servicename;
        }
        prop_check.unput("detach_servicename");
    }

    //Parser of parameter rename_servicename
    {
        if (config.check("rename_servicename"))
        {
            m_rename_servicename = config.find("rename_servicename").asString();
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'rename_servicename' using value:" << m_rename_servicename;
        }
        else
        {
            yCInfo(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "Parameter 'rename_servicename' using DEFAULT value:" << m_rename_servicename;
        }
        prop_check.unput("rename_servicename");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(SimulatedWorld_nws_ros2ParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      SimulatedWorld_nws_ros2_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: SimulatedWorld_nws_ros2\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'node_name': The ROS2 node name\n");
    doc = doc + std::string("'namespace': optional namespace for ros2 node\n");
    doc = doc + std::string("'makesphere_servicename': ROS2 service name for makeSphere\n");
    doc = doc + std::string("'makebox_servicename': ROS2 service name for makeBox\n");
    doc = doc + std::string("'makecylinder_servicename': ROS2 service name for makeCylinder\n");
    doc = doc + std::string("'makeframe_servicename': ROS2 service name for makeFrame\n");
    doc = doc + std::string("'makemodel_servicename': ROS2 service name for makeModel\n");
    doc = doc + std::string("'makeactor_servicename': ROS2 service name for makeActor\n");
    doc = doc + std::string("'changecolor_servicename': ROS2 service name for changeColor\n");
    doc = doc + std::string("'setpose_servicename': ROS2 service name for setPose\n");
    doc = doc + std::string("'enablegravity_servicename': ROS2 service name for enableGravity\n");
    doc = doc + std::string("'enablecollision_servicename': ROS2 service name for enableCollision\n");
    doc = doc + std::string("'getpose_servicename': ROS2 service name for getPose\n");
    doc = doc + std::string("'deleteobject_servicename': ROS2 service name for deleteObject\n");
    doc = doc + std::string("'deleteall_servicename': ROS2 service name for deleteAll\n");
    doc = doc + std::string("'getlist_servicename': ROS2 service name for getList\n");
    doc = doc + std::string("'attach_servicename': ROS2 service name for attach\n");
    doc = doc + std::string("'detach_servicename': ROS2 service name for detach\n");
    doc = doc + std::string("'rename_servicename': ROS2 service name for rename\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device simulatedWorld_nws_ros2 --node_name simulatedWorld_nws_ros2 --namespace <optional_value> --makesphere_servicename makeSphere --makebox_servicename makeBox --makecylinder_servicename makeCylinder --makeframe_servicename makeFrame --makemodel_servicename makeModel --makeactor_servicename makeActor --changecolor_servicename changeColor --setpose_servicename setPose --enablegravity_servicename enableGravity --enablecollision_servicename enableCollision --getpose_servicename getPose --deleteobject_servicename deleteObject --deleteall_servicename deleteAll --getlist_servicename getList --attach_servicename attach --detach_servicename detach --rename_servicename rename\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device simulatedWorld_nws_ros2\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
