/*
 * SPDX-FileCopyrightText: 2026-2026 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Wed Jan 22 12:00:00 2026


#ifndef SIMULATEDWORLD_NWS_ROS2_PARAMSPARSER_H
#define SIMULATEDWORLD_NWS_ROS2_PARAMSPARSER_H

#include <yarp/os/Searchable.h>
#include <yarp/dev/IDeviceDriverParams.h>
#include <string>
#include <cmath>

/**
* This class is the parameters parser for class SimulatedWorld_nws_ros2.
*
* These are the used parameters:
* | Group name | Parameter name | Type   | Units | Default Value            | Required | Description                                           | Notes |
* |:----------:|:--------------:|:------:|:-----:|:------------------------:|:--------:|:-----------------------------------------------------:|:-----:|
* | -          | node_name      | string | -     | simulatedWorld_nws_ros2  | 0        | The ROS2 node name                                    | -     |
* | -          | makesphere     | string | -     | makeSphere               | 0        | ROS2 service name for makeSphere                      | -     |
* | -          | makebox        | string | -     | makeBox                  | 0        | ROS2 service name for makeBox                         | -     |
* | -          | makecylinder   | string | -     | makeCylinder             | 0        | ROS2 service name for makeCylinder                    | -     |
* | -          | makeframe      | string | -     | makeFrame                | 0        | ROS2 service name for makeFrame                       | -     |
* | -          | makemodel      | string | -     | makeModel                | 0        | ROS2 service name for makeModel                       | -     |
* | -          | changecolor    | string | -     | changeColor              | 0        | ROS2 service name for changeColor                     | -     |
* | -          | setpose        | string | -     | setPose                  | 0        | ROS2 service name for setPose                         | -     |
* | -          | enablegravity  | string | -     | enableGravity            | 0        | ROS2 service name for enableGravity                   | -     |
* | -          | enablecollision| string | -     | enableCollision          | 0        | ROS2 service name for enableCollision                 | -     |
* | -          | getpose        | string | -     | getPose                  | 0        | ROS2 service name for getPose                         | -     |
* | -          | deleteobject   | string | -     | deleteObject             | 0        | ROS2 service name for deleteObject                    | -     |
* | -          | deleteall      | string | -     | deleteAll                | 0        | ROS2 service name for deleteAll                       | -     |
* | -          | getlist        | string | -     | getList                  | 0        | ROS2 service name for getList                         | -     |
* | -          | attach         | string | -     | attach                   | 0        | ROS2 service name for attach                          | -     |
* | -          | detach         | string | -     | detach                   | 0        | ROS2 service name for detach                          | -     |
* | -          | rename         | string | -     | rename                   | 0        | ROS2 service name for rename                          | -     |
*
* The device can be launched by yarpdev using one of the following examples (with and without all optional parameters):
* \code{.unparsed}
* yarpdev --device simulatedWorld_nws_ros2 --node_name simulatedWorld_nws_ros2 --makesphere makeSphere --makebox makeBox --makecylinder makeCylinder --makeframe makeFrame --makemodel makeModel --changecolor changeColor --setpose setPose --enablegravity enableGravity --enablecollision enableCollision --getpose getPose --deleteobject deleteObject --deleteall deleteAll --getlist getList --attach attach --detach detach --rename rename
* \endcode
*
* \code{.unparsed}
* yarpdev --device simulatedWorld_nws_ros2
* \endcode
*
*/

class SimulatedWorld_nws_ros2_ParamsParser : public yarp::dev::IDeviceDriverParams
{
public:
    SimulatedWorld_nws_ros2_ParamsParser();
    ~SimulatedWorld_nws_ros2_ParamsParser() override = default;

public:
    const std::string m_device_classname = {"SimulatedWorld_nws_ros2"};
    const std::string m_device_name = {"simulatedWorld_nws_ros2"};
    bool m_parser_is_strict = false;
    struct parser_version_type
    {
         int major = 2;
         int minor = 0;
    };
    const parser_version_type m_parser_version = {};

    std::string m_provided_configuration;

    const std::string m_node_name_defaultValue = {"simulatedWorld_nws_ros2"};
    const std::string m_makesphere_defaultValue = {"makeSphere"};
    const std::string m_makebox_defaultValue = {"makeBox"};
    const std::string m_makecylinder_defaultValue = {"makeCylinder"};
    const std::string m_makeframe_defaultValue = {"makeFrame"};
    const std::string m_makemodel_defaultValue = {"makeModel"};
    const std::string m_changecolor_defaultValue = {"changeColor"};
    const std::string m_setpose_defaultValue = {"setPose"};
    const std::string m_enablegravity_defaultValue = {"enableGravity"};
    const std::string m_enablecollision_defaultValue = {"enableCollision"};
    const std::string m_getpose_defaultValue = {"getPose"};
    const std::string m_deleteobject_defaultValue = {"deleteObject"};
    const std::string m_deleteall_defaultValue = {"deleteAll"};
    const std::string m_getlist_defaultValue = {"getList"};
    const std::string m_attach_defaultValue = {"attach"};
    const std::string m_detach_defaultValue = {"detach"};
    const std::string m_rename_defaultValue = {"rename"};

    std::string m_node_name = {"simulatedWorld_nws_ros2"};
    std::string m_makesphere = {"makeSphere"};
    std::string m_makebox = {"makeBox"};
    std::string m_makecylinder = {"makeCylinder"};
    std::string m_makeframe = {"makeFrame"};
    std::string m_makemodel = {"makeModel"};
    std::string m_changecolor = {"changeColor"};
    std::string m_setpose = {"setPose"};
    std::string m_enablegravity = {"enableGravity"};
    std::string m_enablecollision = {"enableCollision"};
    std::string m_getpose = {"getPose"};
    std::string m_deleteobject = {"deleteObject"};
    std::string m_deleteall = {"deleteAll"};
    std::string m_getlist = {"getList"};
    std::string m_attach = {"attach"};
    std::string m_detach = {"detach"};
    std::string m_rename = {"rename"};

    bool          parseParams(const yarp::os::Searchable & config) override;
    std::string   getDeviceClassName() const override { return m_device_classname; }
    std::string   getDeviceName() const override { return m_device_name; }
    std::string   getDocumentationOfDeviceParams() const override;
    std::vector<std::string> getListOfParams() const override;
    bool getParamValue(const std::string& paramName, std::string& paramValue) const override;
    std::string   getConfiguration() const override;
};

#endif
