/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Mon May 26 22:00:40 2025


#include "Localization2D_nws_ros2_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(Localization2D_nws_ros2ParamsCOMPONENT, "yarp.device.Localization2D_nws_ros2")
}


Localization2D_nws_ros2_ParamsParser::Localization2D_nws_ros2_ParamsParser()
{
}


std::vector<std::string> Localization2D_nws_ros2_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("period");
    params.push_back("node_name");
    params.push_back("ROS::parent_frame_id");
    params.push_back("ROS::child_frame_id");
    return params;
}


bool Localization2D_nws_ros2_ParamsParser::getParamValue(const std::string& paramName, std::string& paramValue) const
{
    if (paramName =="period")
    {
        paramValue = std::to_string(m_period);
        return true;
    }
    if (paramName =="node_name")
    {
        paramValue = m_node_name;
        return true;
    }
    if (paramName =="ROS::parent_frame_id")
    {
        paramValue = m_ROS_parent_frame_id;
        return true;
    }
    if (paramName =="ROS::child_frame_id")
    {
        paramValue = m_ROS_child_frame_id;
        return true;
    }

    yError() <<"parameter '" << paramName << "' was not found";
    return false;

}


std::string Localization2D_nws_ros2_ParamsParser::getConfiguration() const
{
    //This is a sub-optimal solution.
    //Ideally getConfiguration() should return all parameters but it is currently
    //returning only user provided parameters (excluding default values)
    //This behaviour will be fixed in the near future.
    std::string s_cfg = m_provided_configuration;
    return s_cfg;
}

bool      Localization2D_nws_ros2_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(Localization2D_nws_ros2ParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    m_provided_configuration = config.toString();
    yarp::os::Property prop_check(m_provided_configuration.c_str());
    //Parser of parameter period
    {
        if (config.check("period"))
        {
            m_period = config.find("period").asFloat64();
            yCInfo(Localization2D_nws_ros2ParamsCOMPONENT) << "Parameter 'period' using value:" << m_period;
        }
        else
        {
            yCInfo(Localization2D_nws_ros2ParamsCOMPONENT) << "Parameter 'period' using DEFAULT value:" << m_period;
        }
        prop_check.unput("period");
    }

    //Parser of parameter node_name
    {
        if (config.check("node_name"))
        {
            m_node_name = config.find("node_name").asString();
            yCInfo(Localization2D_nws_ros2ParamsCOMPONENT) << "Parameter 'node_name' using value:" << m_node_name;
        }
        else
        {
            yCError(Localization2D_nws_ros2ParamsCOMPONENT) << "Mandatory parameter 'node_name' not found!";
            yCError(Localization2D_nws_ros2ParamsCOMPONENT) << "Description of the parameter: The name of the ROS2 node";
            return false;
        }
        prop_check.unput("node_name");
    }

    //Parser of parameter ROS::parent_frame_id
    {
        yarp::os::Bottle sectionp;
        sectionp = config.findGroup("ROS");
        if (sectionp.check("parent_frame_id"))
        {
            m_ROS_parent_frame_id = sectionp.find("parent_frame_id").asString();
            yCInfo(Localization2D_nws_ros2ParamsCOMPONENT) << "Parameter 'ROS::parent_frame_id' using value:" << m_ROS_parent_frame_id;
        }
        else
        {
            yCError(Localization2D_nws_ros2ParamsCOMPONENT) << "Mandatory parameter 'ROS::parent_frame_id' not found!";
            yCError(Localization2D_nws_ros2ParamsCOMPONENT) << "Description of the parameter: The name of the odom data parent frame";
            return false;
        }
        prop_check.unput("ROS::parent_frame_id");
    }

    //Parser of parameter ROS::child_frame_id
    {
        yarp::os::Bottle sectionp;
        sectionp = config.findGroup("ROS");
        if (sectionp.check("child_frame_id"))
        {
            m_ROS_child_frame_id = sectionp.find("child_frame_id").asString();
            yCInfo(Localization2D_nws_ros2ParamsCOMPONENT) << "Parameter 'ROS::child_frame_id' using value:" << m_ROS_child_frame_id;
        }
        else
        {
            yCError(Localization2D_nws_ros2ParamsCOMPONENT) << "Mandatory parameter 'ROS::child_frame_id' not found!";
            yCError(Localization2D_nws_ros2ParamsCOMPONENT) << "Description of the parameter: The name of the odom data child frame";
            return false;
        }
        prop_check.unput("ROS::child_frame_id");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(Localization2D_nws_ros2ParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(Localization2D_nws_ros2ParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      Localization2D_nws_ros2_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: Localization2D_nws_ros2\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'period': The PeriodicThread period in seconds\n");
    doc = doc + std::string("'node_name': The name of the ROS2 node\n");
    doc = doc + std::string("'ROS::parent_frame_id': The name of the odom data parent frame\n");
    doc = doc + std::string("'ROS::child_frame_id': The name of the odom data child frame\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device localization2D_nws_ros2 --period 0.01 --node_name <mandatory_value> --ROS::parent_frame_id <mandatory_value> --ROS::child_frame_id <mandatory_value>\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device localization2D_nws_ros2 --node_name <mandatory_value> --ROS::parent_frame_id <mandatory_value> --ROS::child_frame_id <mandatory_value>\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
