/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Thu Jan 29 14:11:54 2026


#ifndef FRAMETRANSFORMSET_NWC_ROS2_PARAMSPARSER_H
#define FRAMETRANSFORMSET_NWC_ROS2_PARAMSPARSER_H

#include <yarp/os/Searchable.h>
#include <yarp/dev/IDeviceDriverParams.h>
#include <string>
#include <cmath>

/**
* This class is the parameters parser for class FrameTransformSet_nwc_ros2.
*
* These are the used parameters:
* | Group name | Parameter name   | Type   | Units   | Default Value | Required | Description                                                                                              | Notes |
* |:----------:|:----------------:|:------:|:-------:|:-------------:|:--------:|:--------------------------------------------------------------------------------------------------------:|:-----:|
* | GENERAL    | refresh_interval | double | seconds | 0.1           | 0        | The time interval outside which timed ft will be deleted                                                 | -     |
* | GENERAL    | period           | double | seconds | 0.01          | 0        | The PeriodicThread period in seconds                                                                     | -     |
* | GENERAL    | asynch_pub       | int    | -       | 1             | 0        | If 1, the fts will be published not only every \"period\" seconds but also when set functions are called | -     |
* | ROS2       | ft_node          | string | -       | tfNodeSet     | 0        | The name of the ROS2 node                                                                                | -     |
* | ROS2       | namespace        | string | -       | -             | 0        | optional namespace for ros2 node                                                                         | -     |
* | ROS2       | ft_topic         | string | -       | /tf           | 0        | The name of the ROS2 topic from which fts will be received                                               | -     |
* | ROS2       | ft_topic_static  | string | -       | /tf_static    | 0        | The name of the ROS2 topic from which static fts will be received                                        | -     |
*
* The device can be launched by yarpdev using one of the following examples (with and without all optional parameters):
* \code{.unparsed}
* yarpdev --device frameTransformSet_nwc_ros2 --GENERAL::refresh_interval 0.1 --GENERAL::period 0.01 --GENERAL::asynch_pub 1 --ROS2::ft_node tfNodeSet --ROS2::namespace <optional_value> --ROS2::ft_topic /tf --ROS2::ft_topic_static /tf_static
* \endcode
*
* \code{.unparsed}
* yarpdev --device frameTransformSet_nwc_ros2
* \endcode
*
*/

class FrameTransformSet_nwc_ros2_ParamsParser : public yarp::dev::IDeviceDriverParams
{
public:
    FrameTransformSet_nwc_ros2_ParamsParser();
    ~FrameTransformSet_nwc_ros2_ParamsParser() override = default;

public:
    const std::string m_device_classname = {"FrameTransformSet_nwc_ros2"};
    const std::string m_device_name = {"frameTransformSet_nwc_ros2"};
    bool m_parser_is_strict = false;
    struct parser_version_type
    {
         int major = 2;
         int minor = 0;
    };
    const parser_version_type m_parser_version = {};

    std::string m_provided_configuration;

    const std::string m_GENERAL_refresh_interval_defaultValue = {"0.1"};
    const std::string m_GENERAL_period_defaultValue = {"0.01"};
    const std::string m_GENERAL_asynch_pub_defaultValue = {"1"};
    const std::string m_ROS2_ft_node_defaultValue = {"tfNodeSet"};
    const std::string m_ROS2_namespace_defaultValue = {""};
    const std::string m_ROS2_ft_topic_defaultValue = {"/tf"};
    const std::string m_ROS2_ft_topic_static_defaultValue = {"/tf_static"};

    double m_GENERAL_refresh_interval = {0.1};
    double m_GENERAL_period = {0.01};
    int m_GENERAL_asynch_pub = {1};
    std::string m_ROS2_ft_node = {"tfNodeSet"};
    std::string m_ROS2_namespace = {}; //This default value of this string is an empty string. It is highly recommended to provide a suggested value also for optional string parameters.
    std::string m_ROS2_ft_topic = {"/tf"};
    std::string m_ROS2_ft_topic_static = {"/tf_static"};

    bool          parseParams(const yarp::os::Searchable & config) override;
    std::string   getDeviceClassName() const override { return m_device_classname; }
    std::string   getDeviceName() const override { return m_device_name; }
    std::string   getDocumentationOfDeviceParams() const override;
    std::vector<std::string> getListOfParams() const override;
    bool getParamValue(const std::string& paramName, std::string& paramValue) const override;
    std::string   getConfiguration() const override;
};

#endif
