# Service to be used to retrieve the names of a set of joints
# joints_indexes: it contains the indexes of the joints the user wants to get the names of. If left empty, the names of all the available joints will be returned
int32[] joint_indexes
---
# names: it will cotain the names for the joints specified in "indexes" or for all them if "indexes" is empty
# response: a brief string used to signal the state of the result of the request
# opt_descr: An optional human readable description of the result of the request
string[] names
string response "NOT_SPECIFIED"
string opt_descr
