# Service to get the current velocity for a set of joints
# names: it can contain the names of the joints from which the velocity has to be retrieved. If left empty, the velocity of all the available joints will be returned
string[] names
---
# modes: it will contain the velocity for the joints specified in "names" or for all them if "names" is empty
# response: a brief string used to signal the state of the result of the request
# opt_descr: An optional human readable description of the result of the request
float64[] velocities
string response "NOT_SPECIFIED"
string opt_descr