/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (1.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Wed Aug 28 15:59:35 2024


#include "Rangefinder2D_controlBoard_nws_ros2_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(Rangefinder2D_controlBoard_nws_ros2ParamsCOMPONENT, "yarp.device.Rangefinder2D_controlBoard_nws_ros2")
}


Rangefinder2D_controlBoard_nws_ros2_ParamsParser::Rangefinder2D_controlBoard_nws_ros2_ParamsParser()
{
}


std::vector<std::string> Rangefinder2D_controlBoard_nws_ros2_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("period");
    params.push_back("node_name");
    params.push_back("topic_lidar");
    params.push_back("topic_joint");
    params.push_back("frame_id");
    return params;
}


bool      Rangefinder2D_controlBoard_nws_ros2_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(Rangefinder2D_controlBoard_nws_ros2ParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    std::string config_string = config.toString();
    yarp::os::Property prop_check(config_string.c_str());
    //Parser of parameter period
    {
        if (config.check("period"))
        {
            m_period = config.find("period").asFloat64();
            yCInfo(Rangefinder2D_controlBoard_nws_ros2ParamsCOMPONENT) << "Parameter 'period' using value:" << m_period;
        }
        else
        {
            yCInfo(Rangefinder2D_controlBoard_nws_ros2ParamsCOMPONENT) << "Parameter 'period' using DEFAULT value:" << m_period;
        }
        prop_check.unput("period");
    }

    //Parser of parameter node_name
    {
        if (config.check("node_name"))
        {
            m_node_name = config.find("node_name").asString();
            yCInfo(Rangefinder2D_controlBoard_nws_ros2ParamsCOMPONENT) << "Parameter 'node_name' using value:" << m_node_name;
        }
        else
        {
            yCInfo(Rangefinder2D_controlBoard_nws_ros2ParamsCOMPONENT) << "Parameter 'node_name' using DEFAULT value:" << m_node_name;
        }
        prop_check.unput("node_name");
    }

    //Parser of parameter topic_lidar
    {
        if (config.check("topic_lidar"))
        {
            m_topic_lidar = config.find("topic_lidar").asString();
            yCInfo(Rangefinder2D_controlBoard_nws_ros2ParamsCOMPONENT) << "Parameter 'topic_lidar' using value:" << m_topic_lidar;
        }
        else
        {
            yCInfo(Rangefinder2D_controlBoard_nws_ros2ParamsCOMPONENT) << "Parameter 'topic_lidar' using DEFAULT value:" << m_topic_lidar;
        }
        prop_check.unput("topic_lidar");
    }

    //Parser of parameter topic_joint
    {
        if (config.check("topic_joint"))
        {
            m_topic_joint = config.find("topic_joint").asString();
            yCInfo(Rangefinder2D_controlBoard_nws_ros2ParamsCOMPONENT) << "Parameter 'topic_joint' using value:" << m_topic_joint;
        }
        else
        {
            yCInfo(Rangefinder2D_controlBoard_nws_ros2ParamsCOMPONENT) << "Parameter 'topic_joint' using DEFAULT value:" << m_topic_joint;
        }
        prop_check.unput("topic_joint");
    }

    //Parser of parameter frame_id
    {
        if (config.check("frame_id"))
        {
            m_frame_id = config.find("frame_id").asString();
            yCInfo(Rangefinder2D_controlBoard_nws_ros2ParamsCOMPONENT) << "Parameter 'frame_id' using value:" << m_frame_id;
        }
        else
        {
            yCInfo(Rangefinder2D_controlBoard_nws_ros2ParamsCOMPONENT) << "Parameter 'frame_id' using DEFAULT value:" << m_frame_id;
        }
        prop_check.unput("frame_id");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(Rangefinder2D_controlBoard_nws_ros2ParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(Rangefinder2D_controlBoard_nws_ros2ParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      Rangefinder2D_controlBoard_nws_ros2_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: Rangefinder2D_controlBoard_nws_ros2\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'period': refresh period of the broadcasted values in s\n");
    doc = doc + std::string("'node_name': name of the ros2 node\n");
    doc = doc + std::string("'topic_lidar': name of the topic for lidar data\n");
    doc = doc + std::string("'topic_joint': name of the topic for joints data\n");
    doc = doc + std::string("'frame_id': name of the base frameId\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device rangefinder2D_controlBoard_nws_ros2 --period 0.02 --node_name laser_node --topic_lidar topic_name_lidar --topic_joint topic_lidar_joint --frame_id laser_frame\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device rangefinder2D_controlBoard_nws_ros2\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
