/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Mon May 26 22:00:40 2025


#ifndef RANGEFINDER2D_CONTROLBOARD_NWS_ROS2_PARAMSPARSER_H
#define RANGEFINDER2D_CONTROLBOARD_NWS_ROS2_PARAMSPARSER_H

#include <yarp/os/Searchable.h>
#include <yarp/dev/IDeviceDriverParams.h>
#include <string>
#include <cmath>

/**
* This class is the parameters parser for class Rangefinder2D_controlBoard_nws_ros2.
*
* These are the used parameters:
* | Group name | Parameter name | Type   | Units | Default Value     | Required | Description                                   | Notes |
* |:----------:|:--------------:|:------:|:-----:|:-----------------:|:--------:|:---------------------------------------------:|:-----:|
* | -          | period         | double | s     | 0.02              | 0        | refresh period of the broadcasted values in s | -     |
* | -          | node_name      | string | -     | laser_node        | 0        | name of the ros2 node                         | -     |
* | -          | topic_lidar    | string | -     | topic_name_lidar  | 0        | name of the topic for lidar data              | -     |
* | -          | topic_joint    | string | -     | topic_lidar_joint | 0        | name of the topic for joints data             | -     |
* | -          | frame_id       | string | -     | laser_frame       | 0        | name of the base frameId                      | -     |
*
* The device can be launched by yarpdev using one of the following examples (with and without all optional parameters):
* \code{.unparsed}
* yarpdev --device rangefinder2D_controlBoard_nws_ros2 --period 0.02 --node_name laser_node --topic_lidar topic_name_lidar --topic_joint topic_lidar_joint --frame_id laser_frame
* \endcode
*
* \code{.unparsed}
* yarpdev --device rangefinder2D_controlBoard_nws_ros2
* \endcode
*
*/

class Rangefinder2D_controlBoard_nws_ros2_ParamsParser : public yarp::dev::IDeviceDriverParams
{
public:
    Rangefinder2D_controlBoard_nws_ros2_ParamsParser();
    ~Rangefinder2D_controlBoard_nws_ros2_ParamsParser() override = default;

public:
    const std::string m_device_classname = {"Rangefinder2D_controlBoard_nws_ros2"};
    const std::string m_device_name = {"rangefinder2D_controlBoard_nws_ros2"};
    bool m_parser_is_strict = false;
    struct parser_version_type
    {
         int major = 2;
         int minor = 0;
    };
    const parser_version_type m_parser_version = {};

    std::string m_provided_configuration;

    const std::string m_period_defaultValue = {"0.02"};
    const std::string m_node_name_defaultValue = {"laser_node"};
    const std::string m_topic_lidar_defaultValue = {"topic_name_lidar"};
    const std::string m_topic_joint_defaultValue = {"topic_lidar_joint"};
    const std::string m_frame_id_defaultValue = {"laser_frame"};

    double m_period = {0.02};
    std::string m_node_name = {"laser_node"};
    std::string m_topic_lidar = {"topic_name_lidar"};
    std::string m_topic_joint = {"topic_lidar_joint"};
    std::string m_frame_id = {"laser_frame"};

    bool          parseParams(const yarp::os::Searchable & config) override;
    std::string   getDeviceClassName() const override { return m_device_classname; }
    std::string   getDeviceName() const override { return m_device_name; }
    std::string   getDocumentationOfDeviceParams() const override;
    std::vector<std::string> getListOfParams() const override;
    bool getParamValue(const std::string& paramName, std::string& paramValue) const override;
    std::string   getConfiguration() const override;
};

#endif
