/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Thu Jan 29 14:11:54 2026


#ifndef CONTROLBOARD_NWS_ROS2_PARAMSPARSER_H
#define CONTROLBOARD_NWS_ROS2_PARAMSPARSER_H

#include <yarp/os/Searchable.h>
#include <yarp/dev/IDeviceDriverParams.h>
#include <string>
#include <cmath>

/**
* This class is the parameters parser for class ControlBoard_nws_ros2.
*
* These are the used parameters:
* | Group name | Parameter name | Type   | Units | Default Value | Required | Description                                     | Notes                                                                                   |
* |:----------:|:--------------:|:------:|:-----:|:-------------:|:--------:|:-----------------------------------------------:|:---------------------------------------------------------------------------------------:|
* | -          | node_name      | string | -     | -             | 1        | set the name for ROS node                       | must not start with a leading '/'                                                       |
* | -          | namespace      | string | -     | -             | 0        | optional namespace for ros2 node                | -                                                                                       |
* | -          | topic_name     | string | -     | -             | 1        | set the name for ROS topic                      | must start with a leading '/'                                                           |
* | -          | msgs_name      | string | -     | -             | 0        | set the base name for the topics and interfaces | If it is not specified, the control related topics and services will not be initialized |
* | -          | period         | double | s     | 0.02          | 0        | refresh period of the broadcasted values in s   | optional, default 20ms                                                                  |
*
* The device can be launched by yarpdev using one of the following examples (with and without all optional parameters):
* \code{.unparsed}
* yarpdev --device controlBoard_nws_ros2 --node_name <mandatory_value> --namespace <optional_value> --topic_name <mandatory_value> --msgs_name <optional_value> --period 0.02
* \endcode
*
* \code{.unparsed}
* yarpdev --device controlBoard_nws_ros2 --node_name <mandatory_value> --topic_name <mandatory_value>
* \endcode
*
*/

class ControlBoard_nws_ros2_ParamsParser : public yarp::dev::IDeviceDriverParams
{
public:
    ControlBoard_nws_ros2_ParamsParser();
    ~ControlBoard_nws_ros2_ParamsParser() override = default;

public:
    const std::string m_device_classname = {"ControlBoard_nws_ros2"};
    const std::string m_device_name = {"controlBoard_nws_ros2"};
    bool m_parser_is_strict = false;
    struct parser_version_type
    {
         int major = 2;
         int minor = 0;
    };
    const parser_version_type m_parser_version = {};

    std::string m_provided_configuration;

    const std::string m_node_name_defaultValue = {""};
    const std::string m_namespace_defaultValue = {""};
    const std::string m_topic_name_defaultValue = {""};
    const std::string m_msgs_name_defaultValue = {""};
    const std::string m_period_defaultValue = {"0.02"};

    std::string m_node_name = {}; //This default value is autogenerated. It is highly recommended to provide a suggested value also for mandatory parameters.
    std::string m_namespace = {}; //This default value of this string is an empty string. It is highly recommended to provide a suggested value also for optional string parameters.
    std::string m_topic_name = {}; //This default value is autogenerated. It is highly recommended to provide a suggested value also for mandatory parameters.
    std::string m_msgs_name = {}; //This default value of this string is an empty string. It is highly recommended to provide a suggested value also for optional string parameters.
    double m_period = {0.02};

    bool          parseParams(const yarp::os::Searchable & config) override;
    std::string   getDeviceClassName() const override { return m_device_classname; }
    std::string   getDeviceName() const override { return m_device_name; }
    std::string   getDocumentationOfDeviceParams() const override;
    std::vector<std::string> getListOfParams() const override;
    bool getParamValue(const std::string& paramName, std::string& paramValue) const override;
    std::string   getConfiguration() const override;
};

#endif
