/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Thu Mar 12 20:45:30 2026


#ifndef HAPTICDEVICE_NWS_ROS2_PARAMSPARSER_H
#define HAPTICDEVICE_NWS_ROS2_PARAMSPARSER_H

#include <yarp/os/Searchable.h>
#include <yarp/dev/IDeviceDriverParams.h>
#include <string>
#include <cmath>

/**
* This class is the parameters parser for class HapticDevice_nws_ros2.
*
* These are the used parameters:
* | Group name | Parameter name | Type   | Units | Default Value      | Required | Description                        | Notes |
* |:----------:|:--------------:|:------:|:-----:|:------------------:|:--------:|:----------------------------------:|:-----:|
* | -          | period         | double | s     | 0.02               | 0        | refresh period                     | -     |
* | -          | node_name      | string | -     | haptic_device_ros2 | 0        | name of node                       | -     |
* | -          | namespace      | string | -     | haptic_device_ros2 | 0        | optional namespace for ros2 node   | -     |
* | -          | topic_name     | string | -     | haptic_device_ros2 | 0        | topic name where publish (not '/') | -     |
*
* The device can be launched by yarpdev using one of the following examples (with and without all optional parameters):
* \code{.unparsed}
* yarpdev --device hapticDevice_nws_ros2 --period 0.02 --node_name haptic_device_ros2 --namespace haptic_device_ros2 --topic_name haptic_device_ros2
* \endcode
*
* \code{.unparsed}
* yarpdev --device hapticDevice_nws_ros2
* \endcode
*
*/

class HapticDevice_nws_ros2_ParamsParser : public yarp::dev::IDeviceDriverParams
{
public:
    HapticDevice_nws_ros2_ParamsParser();
    ~HapticDevice_nws_ros2_ParamsParser() override = default;

public:
    const std::string m_device_classname = {"HapticDevice_nws_ros2"};
    const std::string m_device_name = {"hapticDevice_nws_ros2"};
    bool m_parser_is_strict = false;
    struct parser_version_type
    {
         int major = 2;
         int minor = 0;
    };
    const parser_version_type m_parser_version = {};

    std::string m_provided_configuration;

    const std::string m_period_defaultValue = {"0.02"};
    const std::string m_node_name_defaultValue = {"haptic_device_ros2"};
    const std::string m_namespace_defaultValue = {"haptic_device_ros2"};
    const std::string m_topic_name_defaultValue = {"haptic_device_ros2"};

    double m_period = {0.02};
    std::string m_node_name = {"haptic_device_ros2"};
    std::string m_namespace = {"haptic_device_ros2"};
    std::string m_topic_name = {"haptic_device_ros2"};

    bool          parseParams(const yarp::os::Searchable & config) override;
    std::string   getDeviceClassName() const override { return m_device_classname; }
    std::string   getDeviceName() const override { return m_device_name; }
    std::string   getDocumentationOfDeviceParams() const override;
    std::vector<std::string> getListOfParams() const override;
    bool getParamValue(const std::string& paramName, std::string& paramValue) const override;
    std::string   getConfiguration() const override;
};

#endif
